### ISSUE TITLE
The pet model instruction is incorrect

### ISSUE THREAD

**Issue by GojixiaoxinCN** [creepycats/SCPCosmetics#10]
![QQ截图20240113184515](https://github.com/creepycats/SCPCosmetics/assets/145891396/2511306a-c279-40fa-bb3a-c97f60a3c7eb)
The pet model instruction is incorrect

**Comment by creepycats** [comment]
It *is correct*
In the Exiled discord I keep people updated about this, you need one of the newest testing release of MER.

**Comment by GojixiaoxinCN** [comment]
![QQ截图20240115215712](https://github.com/creepycats/SCPCosmetics/assets/145891396/5f7bbb49-8ccc-4abe-882a-60039d33d9d8)
